### ISSUE TITLE
I agree. There is a faster version of matlab file available too.

### ISSUE THREAD

**Issue by kaimex** [Nikeshbajaj/Linear_Feedback_Shift_Register#11]
I agree. There is a faster version of matlab file available too.
Check [function seq = LFSRv3(s,t,N)](https://github.com/Nikeshbajaj/Linear_Feedback_Shift_Register/blob/master/matlabfiles/LFSRv3.m)

Your idea of initializing for fix memory is good too.

To even faster, try python version, that is faster.

_Originally posted by @Nikeshbajaj in https://github.com/Nikeshbajaj/Linear_Feedback_Shift_Register/issues/10#issuecomment-1999810282_

**Comment by kaimex** [comment]
I cannot find any difference between the linked "new" Matlab version LFSRv3 and the the former version.
So it cannot be faster.
Remember: My 2-tap version takes 1.89 s for a 20-bit LFSR and N=300000, your version takes 108.5 s on my PC with my (old) Matlab. N=1000000 took 6.25 s on my PC and was practically impossible with your LFSRv3.
It is very old Matlab advice to avoid any invocation of memory management within for-loops. This will happen anytime when the size of a variable has to increased, as e.g. here the length of the sequence. So it is good practice to initialize variables before the loop to the required final size.

**Comment by Nikeshbajaj** [comment]
Yes, you are right. By initilising vector would help.
I will update these files accrodingly.

Thanks

**Comment by Nikeshbajaj** [comment]
Updated the seq initiliation, however I think, we can keep the generalised version than one for tap-2.

Thanks @kaimex

**Comment by kaimex** [comment]
My personal opinion: nobody really needs an LFSR that requires more than 2 taps, you can always choose the next longer LFSR that gets along with just 2 taps.
