### ISSUE TITLE
[Feature request] Any plan of Galois LFSR implement ?

### ISSUE THREAD

**Issue by tooyangtoonaive** [Nikeshbajaj/Linear_Feedback_Shift_Register#6]
It's more common in computer scene compare with Fibonacci.

**Comment by Nikeshbajaj** [comment]
Good idea! @tooyangtoonaive , shouldn't be difficult to do that.  I will keep that in mind for next release.

Thanks

**Comment by Nikeshbajaj** [comment]
Hi @tooyangtoonaive , I just updated new version 1.0.7 with Implementation of Galois LFSR 

Here is an example

For 5-bit Fibonacci LFSR

```
from pylfsr import LFSR

L = LFSR(fpoly = [5,4,3,2], conf='fibonacci')
L.Viz()
```

Equivalent Galois LFSR is

```
L = LFSR(fpoly = [5,4,3,2], conf='galois')
L.Viz()

```

![Fibonacci LFSR](https://raw.githubusercontent.com/nikeshbajaj/Linear_Feedback_Shift_Register/master/images/FibanacciLFSR_2.gif)

![Galois LFSR](https://raw.githubusercontent.com/nikeshbajaj/Linear_Feedback_Shift_Register/master/images/GaloisLFSR_1.gif)


Thanks for suggestion!
It was fun to implement it :)
